export var GenericArgType;
(function (GenericArgType) {
    GenericArgType["variable"] = "variable";
    GenericArgType["number"] = "number";
    GenericArgType["string"] = "string";
    GenericArgType["boolean"] = "boolean";
    GenericArgType["type"] = "type";
    GenericArgType["building"] = "building";
    GenericArgType["unit"] = "unit";
    GenericArgType["function"] = "function";
    GenericArgType["any"] = "any";
    GenericArgType["null"] = "null";
    GenericArgType["operandTest"] = "operandTest";
    GenericArgType["targetClass"] = "targetClass";
    GenericArgType["unitSortCriteria"] = "unitSortCriteria";
    GenericArgType["valid"] = "valid";
    GenericArgType["operand"] = "operand";
    GenericArgType["lookupType"] = "lookupType";
    GenericArgType["jumpAddress"] = "jumpAddress";
    GenericArgType["buildingGroup"] = "buildingGroup";
    GenericArgType["invalid"] = "invalid";
    GenericArgType["ctype"] = "ctype";
})(GenericArgType || (GenericArgType = {}));
export var CommandErrorType;
(function (CommandErrorType) {
    CommandErrorType[CommandErrorType["argumentCount"] = 0] = "argumentCount";
    CommandErrorType[CommandErrorType["type"] = 1] = "type";
    CommandErrorType[CommandErrorType["noCommand"] = 2] = "noCommand";
    CommandErrorType[CommandErrorType["badStructure"] = 3] = "badStructure";
})(CommandErrorType || (CommandErrorType = {}));
;
